#include %A_LineFile%\..\VARIABLES.ahk
#include %A_LineFile%\..\GLOSSARY.ahk
#include %A_LineFile%\..\KEYMAP.ahk
#include %A_LineFile%\..\REM_AST.ahk
#include %A_LineFile%\..\CLIPBOARD.ahk
#include %A_LineFile%\..\SECRET.ahk
;#include %A_LineFile%\..\.lib\MIDI_LIBS.ahk
#include %A_LineFile%\..\.lib\AHK_CNG-master\src\Class_CNG.ahk
#include D:\______\MACRO_SCRIPTS\AutoHotInterception\Lib\AutoHotInterception.ahk